<?php


namespace app\api\modules\v1;


class Module extends \yii\base\Module
{
    public function init()
    {
//        die('init module');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
//        die('beforeAction');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}